import { test, expect } from '@playwright/test';

test('admin edits course directory and visual markdown, publishes and preserves fold settings', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/login?returnTo=/admin?section=courses');
  await page.getByLabel('邮箱', { exact: true }).fill('admin@example.com');
  await page.getByLabel('密码', { exact: true }).fill('AdminPassword123!');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await page.locator('.course-level-bar .el-radio-button').filter({ hasText: '进阶' }).click();
  await page.getByRole('button', { name: '新增分类', exact: true }).click();
  await page.getByRole('textbox', { name: '分类名称', exact: true }).fill('可视化课程测试');
  await page.getByRole('textbox', { name: '分类英文标识', exact: true }).fill('visual-editor-course');
  await page.locator('.properties-form .el-switch').click();
  await page.getByRole('combobox', { name: '分类状态', exact: true }).press('Enter');
  await page.getByRole('option', { name: '发布', exact: true }).click();
  await page.getByRole('button', { name: /新增条目/ }).click();
  await page.getByRole('textbox', { name: '条目标题', exact: true }).fill('我的第一篇课文');
  await page.getByRole('textbox', { name: '条目英文标识', exact: true }).fill('visual-editor-lesson');
  await page.getByRole('combobox', { name: '条目状态', exact: true }).press('Enter');
  await page.getByRole('option', { name: '发布', exact: true }).click();
  const editor = page.locator('.vditor-wysiwyg [contenteditable="true"]');
  await expect(editor).toBeVisible();
  await editor.fill('直接编辑正文并保存');
  await page.getByRole('button', { name: '保存课程', exact: true }).click();
  await expect(page.getByText('课程已保存', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.locator('.course-directory-table')).not.toContainText('可视化课程测试');
  await page.locator('.course-level-bar .el-radio-button').filter({ hasText: '进阶' }).click();
  await page.getByRole('row').filter({ hasText: '可视化课程测试' }).getByRole('button', { name: '管理分类' }).click();
  await expect(page.getByRole('switch', { name: '允许折叠' })).not.toBeChecked();
  await page.getByRole('row').filter({ hasText: '我的第一篇课文' }).getByRole('button', { name: '编辑内容' }).click();
  await expect(editor).toContainText('直接编辑正文并保存');
  await editor.fill('尚未保存的修改');
  await page.getByRole('button', { name: '用户', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('当前修改尚未保存');
  await page.getByRole('button', { name: '继续编辑', exact: true }).click();
  await expect(page).toHaveURL(/section=courses/);
  await page.getByRole('button', { name: '保存课程', exact: true }).click();
  await expect(page.getByText('课程已保存', { exact: true })).toBeVisible();
  await page.goto('/courses/visual-editor-course');
  await expect(page.locator('.markdown-body')).toContainText('尚未保存的修改');
  const group = page.locator('.course-tree > .el-tree-node').filter({hasText:'可视化课程测试'});
  await group.locator(':scope > .el-tree-node__content').click();
  await expect(group).toHaveAttribute('aria-expanded','true');
  await expect(group.getByRole('link', {name:'我的第一篇课文'})).toBeVisible();
  expect(errors).toEqual([]);
});
