import { test, expect } from '@playwright/test';

test('root entries and category/entry up-down ordering persist and appear in the public directory', async ({ page }) => {
  await page.goto('/login?returnTo=/admin?section=courses');
  await page.getByLabel('邮箱', { exact: true }).fill('admin@example.com');
  await page.getByLabel('密码', { exact: true }).fill('AdminPassword123!');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await page.locator('.course-level-bar .el-radio-button').filter({ hasText: '专业' }).click();
  await page.getByRole('button', {name:'新增无分类条目', exact:true}).click();
  await expect(page.getByLabel('分类名称', {exact:true})).toHaveCount(0);
  await page.getByLabel('条目标题', {exact:true}).fill('独立条目测试');
  await page.getByLabel('条目英文标识', {exact:true}).fill('independent-entry');
  await page.getByRole('combobox', {name:'条目状态'}).press('Enter');
  await page.getByRole('option', {name:'发布',exact:true}).click();
  await page.locator('.editor-shell__content[contenteditable="true"]').fill('无分类正文');
  await page.getByRole('button', {name:'保存课程',exact:true}).click();
  await expect(page.getByText('课程已保存',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'返回列表'}).click();
  const root = page.getByRole('row').filter({hasText:'独立条目测试'});
  await expect(root.getByRole('button',{name:'编辑内容'})).toBeVisible();
  await expect(root.getByRole('button',{name:'管理分类'})).toHaveCount(0);
  await root.getByRole('button',{name:'设为未发表',exact:true}).click();
  await expect(root.getByRole('button',{name:'发布',exact:true})).toBeVisible();
  expect((await page.request.get('/api/v1/courses/independent-entry')).status()).toBe(404);
  await root.getByRole('button',{name:'发布',exact:true}).click();
  await expect(root.getByRole('button',{name:'设为未发表',exact:true})).toBeVisible();
  expect((await page.request.get('/api/v1/courses/independent-entry')).ok()).toBeTruthy();
  const csrf=(await page.context().cookies()).find(c=>c.name==='csrf_token')!.value;
  const response=await page.request.post('/api/v1/admin/courses',{headers:{'X-CSRF-Token':csrf},data:{title:'排序分类测试',slug:'ordering-category',difficulty:'advanced',order_index:999,status:'published',lessons:[{title:'顺序 A',slug:'ordering-a',order_index:0,status:'published'},{title:'顺序 B',slug:'ordering-b',order_index:1,status:'published'}]}});
  expect(response.ok()).toBeTruthy();
  await page.getByRole('button',{name:'刷新数据',exact:true}).click();
  await root.getByRole('button',{name:'下移',exact:true}).click();
  const category=page.getByRole('row').filter({hasText:'排序分类测试'});
  await expect.poll(async()=> (await category.boundingBox())!.y < (await root.boundingBox())!.y).toBeTruthy();
  const child=page.getByRole('row').filter({hasText:'顺序 B'});
  await child.getByRole('button',{name:'上移',exact:true}).click();
  await expect(child.getByRole('button',{name:'上移',exact:true})).toBeDisabled();
  await page.reload();
  await page.locator('.course-level-bar .el-radio-button').filter({hasText:'专业'}).click();
  await expect.poll(async()=> (await category.boundingBox())!.y < (await root.boundingBox())!.y).toBeTruthy();
  await expect(child.getByRole('button',{name:'上移',exact:true})).toBeDisabled();
  await category.getByRole('button',{name:'管理分类',exact:true}).click();
  const categoryChild=page.getByRole('row').filter({hasText:'顺序 B'});
  await categoryChild.getByRole('button',{name:'设为未发表',exact:true}).click();
  await expect(categoryChild.getByRole('button',{name:'发布',exact:true})).toBeVisible();
  const publicCategory=await (await page.request.get('/api/v1/courses/ordering-category')).json();
  expect(publicCategory.lessons.map((item:any)=>item.slug)).not.toContain('ordering-b');
  await categoryChild.getByRole('button',{name:'发布',exact:true}).click();
  await expect(categoryChild.getByRole('button',{name:'设为未发表',exact:true})).toBeVisible();
  await page.goto('/courses/independent-entry');
  await expect(page.locator('.markdown-body')).toContainText('无分类正文');
  const link=page.getByRole('navigation',{name:'课程目录'}).getByRole('link',{name:'独立条目测试',exact:true});
  await expect(link).toBeVisible();
  const node=page.locator('.course-tree > .el-tree-node').filter({has:link});
  await expect(node.locator(':scope > .el-tree-node__children')).toHaveCount(0);
});
