import { expect, test } from '@playwright/test';

test('anonymous visitors open courses directly, switch articles and follow persistent anchors', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: '课程列表', exact: true })).toBeVisible();
  const catalog = await (await page.request.get('/api/v1/courses')).json();
  expect(catalog.length).toBeGreaterThan(1);
  await expect(page.locator('.course-document-row')).toHaveCount(catalog.length);
  await page.getByLabel('搜索课程').fill('no-matching-course-987654');
  await page.getByRole('button', { name: '搜索当前页面', exact: true }).click();
  await expect(page.getByText('没有匹配的课程，试试其他关键词。')).toBeVisible();
  await page.getByLabel('搜索课程').fill('');
  await page.getByRole('button', { name: '搜索当前页面', exact: true }).click();
  await page.locator('.course-document-row').first().click();
  await expect(page).toHaveURL(`/courses/${catalog[0].slug}`);
  await expect(page.locator('.article-head h1')).toHaveText(catalog[0].title);
  await expect(page.locator('.markdown-body article').first()).toBeAttached();
  await expect(page.getByRole('complementary', { name: '本页目录' })).toBeVisible();
  await page.goto(`/courses/${catalog[1].slug}`);
  await expect(page.locator('.article-head h1')).toHaveText(catalog[1].title);
  await page.setViewportSize({ width: 360, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByRole('button', { name: '打开学习目录' }).click();
  await page.getByRole('navigation', { name: '课程目录' }).getByRole('link').first().click();
  await expect(page.locator('.article-head h1')).toHaveText(catalog[0].title);
  await expect(page.locator('.docs-sidebar')).not.toHaveClass(/open/);
  expect(errors).toEqual([]);
});

test('sidebar search updates an already open wiki search page', async ({ page }) => {
  await page.goto('/wiki?q=Git');
  await expect(page.getByLabel('搜索知识库', { exact: true })).toHaveValue('Git');
  await page.getByLabel('搜索知识库', { exact: true }).fill('no-matching-wiki-987654');
  await page.getByRole('button', { name: '搜索当前页面', exact: true }).click();
  await expect(page.getByLabel('搜索知识库', { exact: true })).toHaveValue('no-matching-wiki-987654');
  await expect(page.locator('.status-line')).toContainText('找到 0 个词条');
});

test('header navigation, level filter and reading preferences work and persist', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByRole('link', { name: 'GitHub 项目仓库' })).toHaveAttribute('href', 'https://github.com/arknights8037/VibeCodingWiki');
  const catalog = await (await page.request.get('/api/v1/courses')).json();
  await page.getByRole('combobox', { name: '学习等级', exact: true }).press('Enter');
  await page.getByRole('option', { name: '进阶', exact: true }).click();
  const expected = catalog.filter((course: {difficulty: string}) => course.difficulty === 'intermediate').length;
  await expect(page.locator('.course-document-row')).toHaveCount(expected);
  const expectedLessons = catalog
    .filter((course: {difficulty: string}) => course.difficulty === 'intermediate')
    .reduce((count: number, course: {lessons?: unknown[]}) => count + (course.lessons?.length || 1), 0);
  await expect(page.locator('.docs-course-link')).toHaveCount(expectedLessons);
  await page.reload();
  await expect(page.locator('.level-select')).toContainText('进阶');
  await page.getByRole('button', { name: '皮肤 / Theme' }).click();
  await page.getByRole('menuitem', { name: '深色', exact: true }).click();
  await expect(page.locator('.docs-shell')).toHaveAttribute('data-theme', 'dark');
  await page.getByRole('button', { name: '语言 / Language' }).click();
  await expect(page.locator('.wiki-control-popper.wiki-dark-surface:visible')).toHaveCSS('background-color', 'rgb(43, 46, 39)');
  await page.getByRole('menuitem', { name: 'English UI' }).click();
  await expect(page.getByRole('heading', { name: 'Course library', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.locator('.docs-shell')).toHaveAttribute('data-theme', 'dark');
  await page.getByRole('button', { name: /Settings/ }).click();
  await page.getByRole('combobox', { name: '正文字号', exact: true }).press('Enter');
  await page.getByRole('option', { name: 'Large', exact: true }).click();
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await expect(page.locator('.docs-shell')).toHaveAttribute('data-font', 'large');
  await page.getByRole('button', { name: /Settings/ }).click();
  await page.getByRole('button', { name: 'Reset defaults', exact: true }).click();
  await page.getByRole('button', { name: '完成', exact: true }).click();
  await expect(page.locator('.level-select')).toContainText('全部等级');
  await expect(page.locator('.docs-shell')).toHaveAttribute('data-theme', 'light');
  await page.setViewportSize({ width: 360, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByRole('navigation', { name: '页面切换' }).getByRole('link', { name: '知识库', exact: true }).click();
  await expect(page).toHaveURL('/wiki');
});

test('course groups support persistent fold modes and workspace stays above settings', async ({ page }) => {
  await page.goto('/');
  const group = page.locator('.course-tree > .el-tree-node').first();
  await expect(group.locator(':scope > .el-tree-node__children')).toBeVisible();
  await group.locator(':scope > .el-tree-node__content').click();
  await expect(group.locator(':scope > .el-tree-node__children')).toBeHidden();
  await group.locator(':scope > .el-tree-node__content').click();
  await group.getByRole('link').first().click();
  await expect(page).toHaveURL(/#lesson-/);
  await page.goto('/');
  await page.getByRole('button', { name: /设置/ }).click();
  await page.getByRole('combobox', { name: '目录折叠方式' }).press('Enter');
  await page.getByRole('option', { name: '默认折叠', exact: true }).click();
  await page.getByRole('button', { name: '完成', exact: true }).click();
  await expect(group.locator(':scope > .el-tree-node__children')).toBeHidden();
  await page.reload();
  await expect(group.locator(':scope > .el-tree-node__children')).toBeHidden();
  await page.getByRole('button', { name: /设置/ }).click();
  await page.getByRole('combobox', { name: '目录折叠方式' }).press('Enter');
  await page.getByRole('option', { name: '始终展开，不折叠', exact: true }).click();
  await page.getByRole('button', { name: '完成', exact: true }).click();
  await group.locator(':scope > .el-tree-node__content').click();
  await expect(group).toHaveAttribute('aria-expanded', 'true');
  await expect(group.locator(':scope > .el-tree-node__children')).toBeVisible();
  await page.goto('/login');
  await page.getByLabel('邮箱', { exact: true }).fill('admin@example.com');
  await page.getByLabel('密码', { exact: true }).fill('AdminPassword123!');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page.locator('.sidebar-workspace')).toBeVisible();
  const workspace = await page.locator('.sidebar-workspace').boundingBox();
  const settings = await page.locator('.sidebar-settings').boundingBox();
  expect(workspace!.y + workspace!.height).toBeLessThanOrEqual(settings!.y + 1);
  await expect(page.locator('.sidebar-directory .sidebar-workspace')).toHaveCount(0);
  await expect(page.locator('.level-select .el-select__wrapper')).toHaveCSS('min-height', '36px');
});
