import { expect, test } from '@playwright/test';

test('user creates, publishes, uploads and manages skills', async ({ page, context }) => {
  const account = { email: 'skills-browser@example.com', display_name: '技能作者', password: 'StrongPassword123!' };
  expect((await context.request.post('/api/v1/auth/register', { data: account })).status()).toBe(201);
  expect((await context.request.post('/api/v1/auth/login', { data: account })).status()).toBe(200);
  await page.goto('/skills?create=1');
  await page.getByRole('tab', { name: '在线创建' }).click();
  await page.getByLabel('名称', { exact: true }).fill('browser-skill');
  await page.getByLabel('用途与触发场景').fill('在浏览器测试中创建技能');
  await page.getByLabel('执行说明').fill('# 步骤\n\n执行测试并检查结果。');
  await page.getByLabel('简要说明', { exact: true }).fill('测试技能简要说明');
  await page.getByRole('combobox', { name: '内容分区', exact: true }).click({ force: true });
  await page.getByRole('option').first().click();
  await page.getByRole('button', { name: '保存草稿' }).click();
  const card = page.locator('article.skill-card').filter({ has: page.getByRole('heading', { name: 'browser-skill', exact: true }) });
  await expect(card).toContainText('草稿');
  await card.getByRole('button', { name: '提交审核', exact: true }).click();
  await expect(card).toContainText('待审核');
  await expect(card.getByRole('link', { name: '下载 ZIP' })).toHaveCount(0);
  const adminContext = await context.browser()!.newContext({ baseURL: 'http://127.0.0.1:5174' });
  await adminContext.request.post('/api/v1/auth/login', { data: { email: 'admin@example.com', password: 'AdminPassword123!' } });
  const adminPage = await adminContext.newPage();
  adminPage.setDefaultTimeout(8000);
  async function openReview() {
    await adminPage.goto('/admin');
    await adminPage.getByRole('button', { name: 'Skills', exact: true }).click();
    await adminPage.locator('label.el-radio-button').filter({ hasText: '待审核' }).click();
  }
  await openReview();
  const row = adminPage.getByRole('row').filter({ hasText: 'browser-skill / 1.0.0' });
  await row.getByRole('button', { name: '查看内容' }).click();
  await expect(adminPage.getByRole('dialog')).toContainText('执行测试并检查结果');
  await adminPage.getByRole('dialog').getByRole('button', { name: /close/i }).click();
  await row.getByRole('button', { name: '驳回', exact: true }).click();
  await adminPage.getByRole('dialog').locator('textarea').fill('请补充用途说明');
  await adminPage.getByRole('dialog').getByRole('button', { name: '驳回', exact: true }).click();
  await expect(row).toHaveCount(0);
  await page.reload();
  await page.getByRole('tab', { name: /我的 Skills/ }).click();
  await expect(card).toContainText('已驳回');
  await expect(card).toContainText('请补充用途说明');
  await card.getByRole('button', { name: '提交审核', exact: true }).click();
  await expect(card).toContainText('待审核');
  await openReview();
  await row.getByRole('button', { name: '通过并发布' }).click();
  await expect(row).toHaveCount(0);
  await page.reload();
  await page.getByRole('tab', { name: /我的 Skills/ }).click();
  await expect(card.getByRole('link', { name: '下载 ZIP' })).toBeVisible();
  await card.getByRole('button', { name: '编辑说明' }).click();
  await page.getByRole('dialog').locator('textarea').fill('修改后的简要说明');
  await page.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click();
  await expect(card).toContainText('修改后的简要说明');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(card).toContainText('待审核');
  await expect(card.getByRole('link', { name: '下载 ZIP' })).toHaveCount(0);
  await openReview();
  await row.getByRole('button', { name: '通过并发布' }).click();
  await expect(row).toHaveCount(0);
  await adminContext.close();
  await page.reload();
  await page.getByRole('tab', { name: /我的 Skills/ }).click();
  await expect(card.getByRole('link', { name: '下载 ZIP' })).toBeVisible();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: '.local/skills-desktop.png', fullPage: true, animations: 'disabled' });
  const anonymous = await context.browser()!.newContext();
  const zip = await anonymous.request.get('http://127.0.0.1:5174/skills/browser-skill/1.0.0/download.zip');
  expect(zip.status()).toBe(200);
  expect(zip.headers()['content-type']).toContain('application/zip');
  await anonymous.close();
  await page.goto('/skills?create=1');
  await page.getByLabel('选择 Skill 文件').setInputFiles({ name: 'SKILL.md', mimeType: 'text/markdown', buffer: Buffer.from('---\nname: uploaded-browser-skill\ndescription: 上传测试\n---\n# 步骤\n') });
  await page.getByRole('combobox', { name: '内容分区', exact: true }).click({ force: true });
  await page.getByRole('option').first().click();
  await page.getByRole('button', { name: '保存草稿' }).click();
  await expect(page.locator('article.skill-card').filter({ hasText: 'uploaded-browser-skill' })).toContainText('上传测试');
  await card.getByRole('button', { name: '撤下', exact: true }).click();
  await expect(card).toContainText('草稿');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: '.local/skills-mobile.png', fullPage: true, animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await card.getByRole('button', { name: '删除', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: '删除', exact: true }).click();
  await expect(card).toHaveCount(0);
});
