import { expect, test } from '@playwright/test';

test('minimal skill cards open details from their surface and keep actions independent', async ({ page, context }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('/skills?q=safe-wiki-research');
  const card = page.locator('.skill-card').first();
  await expect(card).toBeVisible();
  await expect(card.locator('.install-url, .checksum')).toHaveCount(0);
  await expect(card.locator('.skill-category')).toHaveText('未分类');
  await expect(card.locator('p')).toHaveCount(1);
  const cardBox = (await card.boundingBox())!;
  const actions = (await card.locator('.skill-actions').boundingBox())!;
  expect(cardBox.height).toBeLessThan(170);
  expect(cardBox.x + cardBox.width - actions.x - actions.width).toBeLessThan(20);
  expect(cardBox.y + cardBox.height - actions.y - actions.height).toBeLessThan(20);
  await card.getByRole('button', { name: '复制安装 URL' }).click();
  await expect(page).toHaveURL('/skills?q=safe-wiki-research');
  await expect(page.locator('.el-message')).toHaveCount(0);
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('/skills/safe-wiki-research/1.0.0/download.zip');
  const download = page.waitForEvent('download');
  await card.getByRole('link', { name: '下载 ZIP' }).click();
  expect((await download).suggestedFilename()).toBe('safe-wiki-research-1.0.0.zip');
  await expect(page).toHaveURL('/skills?q=safe-wiki-research');
  await page.screenshot({ path: '.local/skill-cards-desktop.png', fullPage: true, animations: 'disabled' });
  // This point is in the card padding, outside the title and the buttons.
  await card.click({ position: { x: cardBox.width - 10, y: 12 } });
  await expect(page).toHaveURL('/skills/safe-wiki-research/1.0.0?q=safe-wiki-research');
  await expect(page.locator('.skill-detail .article-head h1')).toHaveText('safe-wiki-research');
  await expect(page.locator('.skill-detail .markdown-body')).toContainText('Summarize the answer');
  await expect(page.locator('.skill-detail .markdown-body')).not.toContainText('compatibility:');
  await page.reload();
  await expect(page.locator('.skill-detail .markdown-body')).toBeVisible();
  await page.screenshot({ path: '.local/skill-detail-desktop.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('link', { name: '返回技能列表' }).click();
  await expect(page.getByLabel('搜索工具', { exact: true })).toHaveValue('safe-wiki-research');
  await card.getByRole('link', { name: 'safe-wiki-research', exact: true }).press('Enter');
  await expect(page.locator('.skill-detail .article-head h1')).toHaveText('safe-wiki-research');
  await page.getByRole('link', { name: '返回技能列表' }).click();
  await page.setViewportSize({ width: 360, height: 800 });
  await expect(card).toBeVisible();
  await expect(page.locator('.el-loading-mask')).toHaveCount(0);
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: '.local/skill-cards-mobile.png', fullPage: true, animations: 'disabled' });
  await card.click({ position: { x: 10, y: 12 } });
  await expect(page.locator('.skill-detail .markdown-body')).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: '.local/skill-detail-mobile.png', fullPage: true, animations: 'disabled' });
  await page.goto('/projects');
  await expect(page.locator('a[href="/projects/submit"]')).toHaveCount(0);
  await page.goto('/login');
  await page.getByLabel('邮箱', { exact: true }).fill('admin@example.com');
  await page.getByLabel('密码', { exact: true }).fill('AdminPassword123!');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await page.goto('/projects');
  await expect(page.locator('a[href="/projects/submit"]')).toHaveCount(0);
  expect(errors).toEqual([]);
});
